#!/bin/bash

set -euo pipefail

if [[ "${PIXEL_FORGE_DISABLE_LANE_DEFAULTS:-0}" == "1" ]]; then
    return 0 2>/dev/null || exit 0
fi

: "${PIXEL_FORGE_LANE:=workstation-v2}"
: "${PIXEL_FORGE_INSTANCE_SLUG:=pixel-forge-workstation-v2}"
: "${PIXEL_FORGE_INSTALL_NAME:=pixel-forge-workstation-v2}"
: "${PIXEL_FORGE_CLI_NAME:=pixel-forge-workstation-v2}"
: "${PIXEL_FORGE_SHELL_NAME:=pixel-forge-workstation-v2-shell}"
: "${PIXEL_FORGE_SERVICE_NAME:=pixel-forge-workstation-v2}"
: "${PIXEL_FORGE_PORT:=7201}"
: "${PIXEL_FORGE_API_PORT:=7201}"
: "${PIXEL_FORGE_WEB_PORT:=5273}"
: "${PIXEL_FORGE_URL_HOST:=pixel-forge-workstation-v2.localhost}"
: "${PIXEL_FORGE_WEB_HOST:=pixel-forge-workstation-v2.localhost}"
: "${PIXEL_FORGE_SHARED_STATE_DIR:=$HOME/.pixel-forge/workstation-v2}"
: "${PIXEL_FORGE_STATE_DIR:=$PIXEL_FORGE_SHARED_STATE_DIR}"
: "${PIXEL_FORGE_RUNTIME_DIR:=$PIXEL_FORGE_SHARED_STATE_DIR/runtime}"
: "${PIXEL_FORGE_LOG_DIR:=$PIXEL_FORGE_RUNTIME_DIR/logs}"
: "${PIXEL_FORGE_SKILLS_INSTALL_DIR:=$PIXEL_FORGE_SHARED_STATE_DIR/skills}"
: "${PIXEL_FORGE_DB_PATH:=$PIXEL_FORGE_SHARED_STATE_DIR/pixel-forge.db}"
: "${PIXEL_FORGE_PID_FILE:=$PIXEL_FORGE_RUNTIME_DIR/${PIXEL_FORGE_SERVICE_NAME}.pid}"
: "${PIXEL_FORGE_LOG_FILE:=$PIXEL_FORGE_RUNTIME_DIR/${PIXEL_FORGE_SERVICE_NAME}.log}"
: "${PIXEL_FORGE_SHELL_URL:=http://${PIXEL_FORGE_URL_HOST}:${PIXEL_FORGE_API_PORT}}"
: "${PIXEL_FORGE_PREVIEW_PARTITION:=persist:${PIXEL_FORGE_INSTANCE_SLUG}-preview}"
: "${PIXEL_FORGE_AGENT_DECK_PROFILE:=workstation-v2}"
: "${PIXEL_FORGE_AGENT_DECK_FOUNDATION_ROOT:=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/foundations/agent-deck}"
: "${PIXEL_FORGE_AGENT_DECK_CMD:=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/agent-deck-workstation-v2.sh}"
: "${PIXEL_FORGE_DESKTOP_ENTRY_NAME:=Pixel Forge Workstation V2}"
: "${PIXEL_FORGE_DESKTOP_FILE_NAME:=pixel-forge-workstation-v2.desktop}"
: "${PIXEL_FORGE_DESKTOP_ICON_NAME:=pixel-forge-workstation-v2}"

export PIXEL_FORGE_LANE
export PIXEL_FORGE_INSTANCE_SLUG
export PIXEL_FORGE_INSTALL_NAME
export PIXEL_FORGE_CLI_NAME
export PIXEL_FORGE_SHELL_NAME
export PIXEL_FORGE_SERVICE_NAME
export PIXEL_FORGE_PORT
export PIXEL_FORGE_API_PORT
export PIXEL_FORGE_WEB_PORT
export PIXEL_FORGE_URL_HOST
export PIXEL_FORGE_WEB_HOST
export PIXEL_FORGE_SHARED_STATE_DIR
export PIXEL_FORGE_STATE_DIR
export PIXEL_FORGE_RUNTIME_DIR
export PIXEL_FORGE_LOG_DIR
export PIXEL_FORGE_SKILLS_INSTALL_DIR
export PIXEL_FORGE_DB_PATH
export PIXEL_FORGE_PID_FILE
export PIXEL_FORGE_LOG_FILE
export PIXEL_FORGE_SHELL_URL
export PIXEL_FORGE_PREVIEW_PARTITION
export PIXEL_FORGE_AGENT_DECK_PROFILE
export PIXEL_FORGE_AGENT_DECK_FOUNDATION_ROOT
export PIXEL_FORGE_AGENT_DECK_CMD
export PIXEL_FORGE_DESKTOP_ENTRY_NAME
export PIXEL_FORGE_DESKTOP_FILE_NAME
export PIXEL_FORGE_DESKTOP_ICON_NAME
export AGENTDECK_PROFILE="$PIXEL_FORGE_AGENT_DECK_PROFILE"
